select *
from ARTICULOS
;

-- lineas albaran compras alm. 90
SELECT SUM(nvl(importe_lin_neto_div,importe_lin_neto) IMPORTE), MIN(DIVISA)
FROM albaran_compras_l
WHERE NUMERO_DOC_INTERNO = '5468' AND CODIGO_EMPRESA = '001'
;

-- LINEAS ALBARAN alm. 00
SELECT CODIGO_ARTICULO, nvl(importe_lin_neto_div,importe_lin_neto) IMPORTE, DIVISA
FROM albaran_compras_l
WHERE NUMERO_DOC_INTERNO = '5582' AND CODIGO_EMPRESA = '001'
;

-- LINEAS ALBARAN alm. 25 DE GASTO EUR
SELECT CODIGO_ARTICULO, nvl(importe_lin_neto_div,importe_lin_neto) IMPORTE, DIVISA
FROM albaran_compras_l
WHERE NUMERO_DOC_INTERNO = '5451' AND CODIGO_EMPRESA = '001'
;

SELECT DIVISA_ORIGEN, 
        DIVISA_DESTINO, 
        FECHA_VALOR,
        VALOR_COMPRA,
        VALOR_VENTA
        FROM (SELECT cambio_divisas.* ,(SELECT lvdiv.nombre FROM divisas lvdiv WHERE lvdiv.codigo = cambio_divisas.divisa_destino) D_DIVISA_DESTINO,(SELECT lvdiv.nombre FROM divisas lvdiv WHERE lvdiv.codigo = cambio_divisas.divisa_origen) D_DIVISA_ORIGEN FROM cambio_divisas) cambio_divisas 
        where fecha_valor >= '01/02/2025' 
        order by fecha_valor asc;


SELECT GC1,D_GC1,GC2, GN1 FROM (SELECT EMPRESA GC1,DECODE(froxa_seguros_cambio.empresa,NULL,NULL,(SELECT lvemp.nombre FROM empresas_conta lvemp WHERE lvemp.codigo = froxa_seguros_cambio.empresa)) D_GC1,PERIODO GC2,CAMBIO GN1,NULL GN2,NULL GN3,NULL GN4,NULL GN5,NULL GN6,NULL GN7,NULL GN8,NULL GN9,NULL GN10,NULL GN11,NULL GN12,NULL GN13,NULL GN14,NULL GN15,NULL GN16,NULL GN17,NULL GN18,NULL GN19,NULL GN20,NULL GN21,NULL GN22,NULL GN23,NULL GN24,NULL GN25,NULL GC3,NULL GC4,NULL GC5,NULL GC6,NULL GC7,NULL GC8,NULL GC9,NULL GC10,NULL GC11,NULL GC12,NULL GC13,NULL GC14,NULL GC15,NULL GC16,NULL GC17,NULL GC18,NULL GC19,NULL GC20,NULL GC21,NULL GC22,NULL GC23,NULL GC24,NULL GC25,NULL GD1,NULL GD2,NULL GD3,NULL GD4,NULL GD5,NULL GD6,NULL GD7,NULL GD8,NULL GD9,NULL GD10,NULL GD11,NULL GD12,NULL GD13,NULL GD14,NULL GD15,NULL GD16,NULL GD17,NULL GD18,NULL GD19,NULL GD20,NULL GD21,NULL GD22,NULL GD23,NULL GD24,NULL GD25,NULL GCHECK1,NULL GCHECK2,NULL GCHECK3,NULL GCHECK4,NULL GCHECK5,NULL GCHECK6,NULL GCHECK7,NULL GCHECK8,NULL GCHECK9,NULL GCHECK10,NULL GCHECK11,NULL GCHECK12,NULL GCHECK13,NULL GCHECK14,NULL GCHECK15,NULL GCHECK16,NULL GCHECK17,NULL GCHECK18,NULL GCHECK19,NULL GCHECK20,NULL GCHECK21,NULL GCHECK22,NULL GCHECK23,NULL GCHECK24,NULL GCHECK25,NULL N1,NULL N2,NULL N3,NULL N4,NULL N5,NULL N6,NULL N7,NULL N8,NULL N9,NULL N10,NULL N11,NULL N12,NULL N13,NULL N14,NULL N15,NULL N16,NULL N17,NULL N18,NULL N19,NULL N20,NULL N21,NULL N22,NULL N23,NULL N24,NULL N25,NULL N26,NULL N27,NULL N28,NULL N29,NULL N30,NULL C1,NULL C2,NULL C3,NULL C4,NULL C5,NULL C6,NULL C7,NULL C8,NULL C9,NULL C10,NULL C11,NULL C12,NULL C13,NULL C14,NULL C15,NULL C16,NULL C17,NULL C18,NULL C19,NULL C20,NULL C21,NULL C22,NULL C23,NULL C24,NULL C25,NULL C26,NULL C27,NULL C28,NULL C29,NULL C30,NULL D1,NULL D2,NULL D3,NULL D4,NULL D5,NULL D6,NULL D7,NULL D8,NULL D9,NULL D10,NULL D11,NULL D12,NULL D13,NULL D14,NULL D15,NULL D16,NULL D17,NULL D18,NULL D19,NULL D20,NULL D21,NULL D22,NULL D23,NULL D24,NULL D25,NULL D26,NULL D27,NULL D28,NULL D29,NULL D30,NULL CHECK1,NULL CHECK2,NULL CHECK3,NULL CHECK4,NULL CHECK5,NULL CHECK6,NULL CHECK7,NULL CHECK8,NULL CHECK9,NULL CHECK10,NULL CHECK11,NULL CHECK12,NULL CHECK13,NULL CHECK14,NULL CHECK15,NULL CHECK16,NULL CHECK17,NULL CHECK18,NULL CHECK19,NULL CHECK20,NULL CHECK21,NULL CHECK22,NULL CHECK23,NULL CHECK24,NULL CHECK25,NULL CHECK26,NULL CHECK27,NULL CHECK28,NULL CHECK29,NULL CHECK30,NULL LIST1,NULL LIST2,NULL LIST3,NULL LIST4,NULL LIST5,NULL LIST6,NULL LIST7,NULL LIST8,NULL LIST9,NULL LIST10,NULL TEXTAREA1,NULL TEXTAREA2,NULL D_GC2,NULL D_GC3,NULL D_GC4,NULL D_GC5,NULL D_GC6,NULL D_GC7,NULL D_GC8,NULL D_GC9,NULL D_GC10,NULL D_GC11,NULL D_GC12,NULL D_GC13,NULL D_GC14,NULL D_GC15,NULL D_GC16,NULL D_GC17,NULL D_GC18,NULL D_GC19,NULL D_GC20,NULL D_GC21,NULL D_GC22,NULL D_GC23,NULL D_GC24,NULL D_GC25,NULL D_GN0,NULL D_GN1,NULL D_GN2,NULL D_GN3,NULL D_GN4,NULL D_GN5,NULL D_GN6,NULL D_GN7,NULL D_GN8,NULL D_GN9,NULL D_GN10,NULL D_GN11,NULL D_GN12,NULL D_GN13,NULL D_GN14,NULL D_GN15,NULL D_GN16,NULL D_GN17,NULL D_GN18,NULL D_GN19,NULL D_GN20,NULL D_GN21,NULL D_GN22,NULL D_GN23,NULL D_GN24,NULL D_GN25,NULL D_C1,NULL D_C2,NULL D_C3,NULL D_C4,NULL D_C5,NULL D_C6,NULL D_C7,NULL D_C8,NULL D_C9,NULL D_C10,NULL D_C11,NULL D_C12,NULL D_C13,NULL D_C14,NULL D_C15,NULL D_C16,NULL D_C17,NULL D_C18,NULL D_C19,NULL D_C20,NULL D_C21,NULL D_C22,NULL D_C23,NULL D_C24,NULL D_C25,NULL D_C26,NULL D_C27,NULL D_C28,NULL D_C29,NULL D_C30,NULL D_N1,NULL D_N2,NULL D_N3,NULL D_N4,NULL D_N5,NULL D_N6,NULL D_N7,NULL D_N8,NULL D_N9,NULL D_N10,NULL D_N11,NULL D_N12,NULL D_N13,NULL D_N14,NULL D_N15,NULL D_N16,NULL D_N17,NULL D_N18,NULL D_N19,NULL D_N20,NULL D_N21,NULL D_N22,NULL D_N23,NULL D_N24,NULL D_N25,NULL D_N26,NULL D_N27,NULL D_N28,NULL D_N29,NULL D_N30,NULL GN0,NULL GD0,rowid int_rowid FROM FROXA_SEGUROS_CAMBIO) FROXA_SEGUROS_CAMBIO WHERE 8=8 order by GC2 DESC;


SELECT GC1 EMPRESA, D_GC1 NOMBRE, GC2 FECHA, GN1 VALOR_CAMBIO
FROM (
    SELECT EMPRESA GC1,
           DECODE(froxa_seguros_cambio.empresa,NULL,NULL,
                  (SELECT lvemp.nombre 
                     FROM empresas_conta lvemp 
                    WHERE lvemp.codigo = froxa_seguros_cambio.empresa)) D_GC1,
           PERIODO GC2,
           CAMBIO GN1
    FROM FROXA_SEGUROS_CAMBIO
    ORDER BY PERIODO DESC
)
WHERE ROWNUM = 1;



SELECT
  (SELECT fam.descripcion 
    FROM familias fam where fam.numero_tabla = '7' AND fam.codigo_familia = (
      SELECT artic.codigo_estad7  FROM ARTICULOS artic WHERE artic.CODIGO_ARTICULO =  om.CODIGO_COMPONENTE  AND ROWNUM = 1 )) AS tipo_descr,
  (SELECT TO_CHAR(OFB.FECHA_INI_FABRI, 'YYYY-MM-DD') FROM ORDENES_FABRICA_CAB OFB WHERE OFB.ORDEN_DE_FABRICACION = om.ORDEN_DE_FABRICACION) AS FECHA_INI_FABRI,
  ((SELECT descrip_comercial FROM articulos artx WHERE artx.CODIGO_ARTICULO = om.CODIGO_COMPONENTE)  || ' ' || om.CODIGO_COMPONENTE) AS NOMBRE_ARTICULO,      
  om.CODIGO_PRESENTACION_COMPO,
  TO_NUMBER(om.CANT_REAL_CONSUMO_UNIDAD1) CANTIDAD_UNIDAD1,
  om.ORDEN_DE_FABRICACION,
  (SELECT f.descripcion FROM familias f WHERE f.numero_tabla = '1' AND f.codigo_empresa = '001' AND f.codigo_familia = (
       SELECT a.codigo_familia FROM articulos a WHERE a.codigo_articulo = om.CODIGO_COMPONENTE AND a.codigo_empresa = '001')
  ) AS D_CODIGO_FAMILIA,
  (SELECT f2.descripcion FROM familias f2 WHERE f2.numero_tabla = '2' AND f2.codigo_empresa = '001' AND f2.codigo_familia = (
       SELECT a2.codigo_estad2 FROM articulos a2 WHERE a2.codigo_articulo = om.CODIGO_COMPONENTE AND a2.codigo_empresa = '001')
  ) AS SUBFAMILIA
FROM OF_MATERIALES_UTILIZADOS om;



-- viejo

 SELECT
  (SELECT descripcion 
    FROM familias where numero_tabla = '7' AND codigo_familia = (
      SELECT a.codigo_estad7 
      FROM ARTICULOS a 
      WHERE a.CODIGO_ARTICULO = c.CODIGO_ARTICULO_CONSUMIDO AND ROWNUM = 1
    )) AS tipo_descr,
  (SELECT TO_CHAR(OFB.FECHA_INI_FABRI, 'YYYY-MM-DD') FROM ORDENES_FABRICA_CAB OFB WHERE OFB.ORDEN_DE_FABRICACION = c.ORDEN_DE_FABRICACION) AS FECHA_INI_FABRI,
  ((SELECT descrip_comercial FROM articulos artx WHERE artx.CODIGO_ARTICULO = c.CODIGO_ARTICULO_CONSUMIDO) || ' ' || CODIGO_ARTICULO_CONSUMIDO) AS NOMBRE_ARTICULO,  
  (
    SELECT ar.unidad_codigo1
    FROM articulos ar
    WHERE ar.codigo_articulo = c.CODIGO_ARTICULO_CONSUMIDO AND ar.codigo_empresa = '001'
  ) AS CODIGO_PRESENTACION_COMPO,
  TO_NUMBER(c.CANTIDAD_UNIDAD1) AS CANTIDAD_UNIDAD1,
  c.ORDEN_DE_FABRICACION,
  (
    SELECT f.descripcion
    FROM familias f
    WHERE f.numero_tabla = '1' AND f.codigo_empresa = '001'
      AND f.codigo_familia = (
        SELECT a.codigo_familia
        FROM articulos a
        WHERE a.codigo_articulo = c.CODIGO_ARTICULO_CONSUMIDO
          AND a.codigo_empresa = '001'
      )
  ) AS D_CODIGO_FAMILIA,
  (
    SELECT f2.descripcion
    FROM familias f2
    WHERE f2.numero_tabla = '2' AND f2.codigo_empresa = '001' AND f2.codigo_familia = (
        SELECT a2.codigo_estad2
        FROM articulos a2
        WHERE a2.codigo_articulo = c.CODIGO_ARTICULO_CONSUMIDO AND a2.codigo_empresa = '001'
      )
  ) AS SUBFAMILIA
FROM COSTES_ORDENES_FAB_MAT_CTD c;


select *
from ORDENES_FABRICA_CAB;

select COSTES_ORDENES_FAB_MAT_CTD.ORDEN_DE_FABRICACION, CANTIDAD_UNIDAD1 -- 27000
from COSTES_ORDENES_FAB_MAT_CTD
join ORDENES_FABRICA_CAB ofc on ofc.ORDEN_DE_FABRICACION = COSTES_ORDENES_FAB_MAT_CTD.ORDEN_DE_FABRICACION
where ofc.FECHA_INI_FABRI >= to_date('2025-07-01','YYYY-MM-DD')
and ofc.FECHA_INI_FABRI <= to_date('2025-07-31','YYYY-MM-DD')
and COSTES_ORDENES_FAB_MAT_CTD.CODIGO_ARTICULO_CONSUMIDO = '40095'
;


select  SUM(CANT_REAL_CONSUMO_UNIDAD1) 
from OF_MATERIALES_UTILIZADOS
where CODIGO_COMPONENTE = '40095'
and fecha_fabricacion >= to_date('2025-07-01','YYYY-MM-DD')
and fecha_fabricacion <= to_date('2025-07-31','YYYY-MM-DD')
-- GROUP BY ORDEN_DE_FABRICACION
; 