# Generated by Django 5.2.1 on 2025-05-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCostsHead',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('article_code', models.CharField(max_length=22, unique=True)),
                ('article_name', models.TextField(null=True)),
                ('old_art_code', models.CharField(max_length=22, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleCostsLines',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('costs_id', models.BigIntegerField(null=True)),
                ('article_code', models.CharField(max_length=22)),
                ('article_name', models.TextField(null=True)),
                ('percentage', models.IntegerField(null=True)),
                ('alternative', models.TextField(null=True)),
                ('state', models.TextField(null=True)),
            ],
        ),
    ]
