# Generated by Django 5.2.1 on 2025-05-23 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecostslines',
            name='state',
        ),
    ]
